### ISSUE TITLE
Focal plane resolution patch

### ISSUE THREAD

**Issue by cdcseacave** [mayanklahiri/easyexif#1]
Hi,

Thank you for the great EXIF lib, it is exactly what I needed: small and working.

I just needed some more fields very important for my Structure-from-Motion app, like "Focal plane resolution" and GPS precision, which were very easy to add. If you think it's worthy, please find included the link to the patch.

https://drive.google.com/file/d/0B8bb0qT4PvT8OFZOdkdCdlkwQkE/view?usp=sharing

Cheers!

**Comment by mayanklahiri** [comment]
Hi there,

Please feel free to submit a pull request if you've already implemented this. Unfortunately, I can only accept pull requests for this project at the moment.

**Comment by cdcseacave** [comment]
Sry, I do not want to fork the project only to submit this patch, and other method I do not know to make a pull request.

Please note also that the JPG parsing is sometimes failing, when the file does not end by EOS (it is possible to end in 0xFF added as padding to EOS).

**Comment by volftomas** [comment]
@cdcseacave Can you make a new issue about the parsing problem and attach image to reproduce it? Thanks

**Comment by cdcseacave** [comment]
I created a new issue, however I do not find anymore the sample image. However there is nothing very special about that image, it simply adds 0xFF padding to all segments as described in the JPG format.
