### ISSUE TITLE
test-images/*.expected files contain binary strings

### ISSUE THREAD

**Issue by pvanek** [mayanklahiri/easyexif#10]
There are some strange binary chars in GPS Latitude and GPS Longitude 

When I open it in vim:

```
GPS Latitude         : 0.000000 deg (0.000000 deg, 0.000000 min, 0.000000 sec ^@)
GPS Longitude        : 0.000000 deg (0.000000 deg, 0.000000 min, 0.000000 sec ^@)
```

Is there any special reason for these chars? Or can it be removed?

**Comment by mayanklahiri** [comment]
Looks like the ^@ is a 0-byte that was being left at its initial value when the image doesn't have any GPS data. I'll update this to put something more ASCII-friendly, like a '?' character perhaps.
