### ISSUE TITLE
Unable to read the GPS location of Images (BB Android)

### ISSUE THREAD

**Issue by nareshmember** [mayanklahiri/easyexif#12]
Hello Sir,

The source code unable to read the GPS location (Images taken by Blackberry Android phones).

in line 797 of your code

case 4:
          // GPS longitude
          if (format == 5 && length == 3) {

But BB Android Images format is 10.

Please check once. Here I am attaching a sample image.

Regards
naresh

![4711](https://cloud.githubusercontent.com/assets/5907794/13141030/7e3cd694-d635-11e5-97ba-21c47886ad12.jpg)

**Comment by mayanklahiri** [comment]
Thanks for reporting Naresh, putting in a patch now.
