### ISSUE TITLE
Try to run on eclispe but couldnot run

### ISSUE THREAD

**Issue by jyotiad18** [mayanklahiri/easyexif#14]
I Try to complie in my eclipse project , Couldnot complie it.
Any suggestion??

**Comment by pmoulon** [comment]
Can you share the compiler log?

**Comment by jyotiad18** [comment]
when i put your exif.cpp it's give alot of error .

**Comment by pmoulon** [comment]
You need to activate C++11 support.

**Comment by jyotiad18** [comment]
I am trying .
Thank you for your quick response.

Thank you again.

**Comment by jyotiad18** [comment]
thank  you it's working .

**Comment by pmoulon** [comment]
Can you please close the issue.
