### ISSUE TITLE
demo in repository

### ISSUE THREAD

**Issue by volftomas** [mayanklahiri/easyexif#5]
Is there a reason why demo should be in the repository?

It's linux only, could be compiled so it won't run on other machine and it is changed in nearly every commit which runs test.sh.

IMHO it should be just removed (expecially since running `make` takes like 2 seconds even on my weak netbook).

**Comment by mayanklahiri** [comment]
Fine with me -- feel free to delete it.

**Comment by volftomas** [comment]
Ok, will do.
