### ISSUE TITLE
Parse JPG

### ISSUE THREAD

**Issue by cdcseacave** [mayanklahiri/easyexif#7]
The JPG parsing is sometimes failing, when the file does not end by EOS (it is possible to end in 0xFF added as padding to EOS).

**Comment by volftomas** [comment]
Just to make clear, by "failing" you mean
a) no data parsed
b) only some data parsed
c) crash
d) ?

Thanks

**Comment by cdcseacave** [comment]
ok, to be clear, line 165 in cpp is not always right

**Comment by volftomas** [comment]
JPEG image stream should start with SOI (FFD8) and end with EOI (FFD9), at least if I read the standard correctly. And as far as I can tell, `int EXIFInfo::parseFrom(const unsigned char *buf, unsigned len)` is called only once with whole image as it's argument.

So padding after EOS (btw I didn't find what that marker is) should have no effect on line 165.
